name: build-for-all-machines
on: [push, workflow_dispatch]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
#      - name: Checkout
      - uses: actions/checkout@v3
#      - name: Set up Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
#      - name: Install dependencies
      - run: python -m pip install pygame appdirs pyinstaller
#      - name: Build for Windows
      - run: python buildWin.py
#      - name: Compress ZIP...
      - run: powershell Compress-Archive dist/* SpacebarClicker-Windows.zip
#      - name: ...and upload!
      - uses: actions/upload-artifact@v3
        with:
          name: SpacebarClicker-Windows
          path: dist/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
      - uses: actions/checkout@v3
#      - name: Set up Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
#      - name: Install dependencies
      - run: python -m pip install pygame appdirs pyinstaller
#      - name: Build for Linux
      - run: python build.py
#      - name: Compress ZIP...
#      - run: cd dist && zip -r SpacebarClicker-Linux.zip *
#      - name: ...and upload!
      - uses: actions/upload-artifact@v3
        with:
          name: SpacebarClicker-Linux
          path: dist/*

  build-macOS:
    runs-on: macos-11
    steps:
      #      - name: Checkout
      - uses: actions/checkout@v3
      #      - name: Set up Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      #      - name: Install dependencies
      - run: python -m pip install pygame appdirs pyinstaller
      #      - name: Build for Linux
      - run: python build.py
      #      - name: Compress ZIP...
#      - run: cd dist && zip -r SpacebarClicker-macOS.zip *
      #      - name: ...and upload!
      - uses: actions/upload-artifact@v3
        with:
          name: SpacebarClicker-macOS
          path: dist/*