name: Build and Upload
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build for Windows
        run: python buildWin.py

      - name: And upload!
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: dist/*

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build for Linux
        run: python build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: dist/*

  build-macOS:
    name: Build for macOS
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build for Mac
        run: python build.py

      - name: Fix Permissions
        run: chmod +x dist/SpacebarClicker.app/Contents/MacOS/SpacebarClicker

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: macOS
          path: dist/*